# service account-name
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
    app: {{ .Release.Name }}

---
# task service account token
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sa
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-sa
type: kubernetes.io/service-account-token
