apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-http-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-http-server
  ports:
  - name: http
    protocol: TCP
    port: 8937
    targetPort: 8937
